### PR TITLE
kpi: update module versions (also dbsetup)

### PR DESCRIPTION
**Pull request by Lodifice**
Will this update dbsetup or how is the staging database handled nowadays?

### CODE REVIEW

**Comment by inyono** [comment]
DbSetup only triggers if the database is empty. Instead, we probably want a k8s cronjob that replaces the dev / staging DB every night with the current anonymized dump, right? Could add that as a task

**Comment by Lodifice** [comment]
I have changed dbsetup quite a bit so that it triggers when there is a new dump available.
In the long run your're right and we should definitely setup a k8 cronjob for this.
I may look into that after the current tasks are done.

**Comment by inyono** [comment]
Ah, forgot to check the current master of the images repository. Then it should work.

**Comment by inyono** [comment]
Applied

**Pull request merged**
